version: "3.3"
services:
  webserver:
    image: php:7.2-apache
    build: 
      context: ./bin/webserver
    container_name: 'webserver-apache-dev'
    restart: 'always'
    ports:
      #- "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "80:80"
      #- "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${DOCKER_SCRIPTS-./config/scripts}:/var/docker-scripts
  db:
    image: mysql:5.7
    restart: always
    container_name: 'db-mysql-dev'
    networks:
      default:
        ipv4_address: 172.20.0.3
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
  Redis:
    image: redis
    restart: always
    container_name: 'redis-dev'
    ports:
    - "6379:6379"
    volumes:
    - ${MYSQL_DATA_DIR-./data/redis}:/var/lib/redis
